### ISSUE TITLE
Debugger Breakpoint Error

### ISSUE THREAD

**Issue by benfrancis** [mozilla/qbrt#19] opened 2017-03-17 09:53 UTC
I may have found my first bug...

STR:
* Start the qbrt runtime with a chrome application
* Set a breakpoint in the debugger
* Trigger code at breakpoint

Expected:
* Execution stops at breakpoint

Actual:
* Error in console "TypeError: value.constructor is undefined[Learn More]  debugger.js:31325:1"

**Comment by mykmelez** [comment] 2017-03-18 01:29
It looks like this is caused by https://github.com/devtools-html/debugger.html/issues/2407, which I've proposed fixing by https://github.com/devtools-html/debugger.html/pull/2408.

I suspect an underlying issue, perhaps because of the way that qbrt references devtools files, or perhaps because qbrt uses `about:devtools-toolbox?type=window`, which isn't in use elsewhere and thus is an untested code path (as far as I know; Positron used to use it, but not the version that is now landed in Firefox, and presumably with the old debugger).

cc: @jryans in case he has insight about the potential underlying issue.

**Comment by jasonLaster** [comment] 2017-03-18 12:36
Thanks @benfrancis, @mykmelez. 

Could you share so context on [qbrt](https://www.npmjs.com/package/qbrt) and how you're testing applications with the toolbox?

**Comment by mykmelez** [comment] 2017-03-20 20:23
@jasonLaster On the [example-app-breakable branch](https://github.com/mykmelez/qbrt/tree/example-app-breakable), I've modified the app in the example/ directory to include an event listener function that gets called when I click anywhere in the app's window. After starting the app with `qbrt run example/`, I set a breakpoint in that function and then click in the window.

Without the debugger.html fix, that results in the error message reported in this issue, and the debugger doesn't stop at the breakpoint. With that fix, the message doesn't appear, and the debugger stops.

**Comment by mykmelez** [comment] 2017-03-29 17:22
Note: over in the [DevTools Slack](https://devtools-html.slack.com), I asked when the debugger.html frontend would be updated in mozilla-central, and @jasonLaster said it'll likely happen early next week. I'll resolve this issue once that's happened and I've verified that a qbrt update pulls a nightly build of the runtime with the fix.

**Comment by mykmelez** [comment] 2017-05-15 23:50
> On the example-app-breakable branch

Note for posterity: I've since merged that branch into master and deleted it, so the link no longer works, but you can now test this via a standard build of qbrt.

> I'll resolve this issue once that's happened and I've verified that a qbrt update pulls a nightly build of the runtime with the fix.

I've now verified this, so I'm resolving the issue!

**Closed by mykmelez** 2017-05-15 23:50 UTC

**Comment by benfrancis** [comment] 2017-05-17 15:01
@mykmelez Yep, this is working for me too now. Thanks!
